// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyF5vFmc0sTz1FfPPpM5IwtUqavw3Vueg',
    appId: '1:480484065193:web:f6bddbad03addf095d8eb8',
    messagingSenderId: '480484065193',
    projectId: 'mychatapp-88e5f',
    authDomain: 'mychatapp-88e5f.firebaseapp.com',
    storageBucket: 'mychatapp-88e5f.appspot.com',
    measurementId: 'G-7XFLXRKP7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc1LLW8eEAmaUQ-iQ99idFaJGvSaxSUDw',
    appId: '1:480484065193:android:e7c9cb26eda506495d8eb8',
    messagingSenderId: '480484065193',
    projectId: 'mychatapp-88e5f',
    storageBucket: 'mychatapp-88e5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2EXUNGufAISnPMge0eelhEChqOEk8Y6M',
    appId: '1:480484065193:ios:269d9c06f9bed75a5d8eb8',
    messagingSenderId: '480484065193',
    projectId: 'mychatapp-88e5f',
    storageBucket: 'mychatapp-88e5f.appspot.com',
    iosBundleId: 'com.example.mychatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2EXUNGufAISnPMge0eelhEChqOEk8Y6M',
    appId: '1:480484065193:ios:269d9c06f9bed75a5d8eb8',
    messagingSenderId: '480484065193',
    projectId: 'mychatapp-88e5f',
    storageBucket: 'mychatapp-88e5f.appspot.com',
    iosBundleId: 'com.example.mychatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyF5vFmc0sTz1FfPPpM5IwtUqavw3Vueg',
    appId: '1:480484065193:web:bf066732b3d966b15d8eb8',
    messagingSenderId: '480484065193',
    projectId: 'mychatapp-88e5f',
    authDomain: 'mychatapp-88e5f.firebaseapp.com',
    storageBucket: 'mychatapp-88e5f.appspot.com',
    measurementId: 'G-VJX31YZ5JZ',
  );
}
